name: Run Tests

on:
  push:
    branches:
      - "*"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Ruby head
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby

      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install --frozen-lockfile
      
      - name: Run tests
        run: bundle exec rake
